language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO=django==1.3.7
  - DJANGO=django==1.4.12
  - DJANGO=django==1.5.7
  - DJANGO=django==1.6.4
  - DJANGO=https://github.com/django/django/tarball/stable/1.7.x
install:
  - pip install -q $DJANGO && pip install sphinx argparse
  - python setup.py -q install
script: python runtests.py
matrix:
  exclude:
    - python: 3.4
      env: DJANGO=django==1.6.4
    - python: 3.4
      env: DJANGO=django==1.5.7
    - python: 3.4
      env: DJANGO=django==1.4.12
    - python: 3.4
      env: DJANGO=django==1.3.7
    - python: 3.3
      env: DJANGO=django==1.4.12
    - python: 3.3
      env: DJANGO=django==1.3.7
    - python: 2.6
      env: DJANGO=https://github.com/django/django/tarball/stable/1.7.x
    - python: 2.6
      env: DJANGO=django==1.6.4
